version: "3"

services:
  # Setup backend
  server:
    build: "./backend"
    expose:
      - ${API_PORT}
    environment:
      - API_PORT=${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./backend/src:/srv/app/id2207-backend/src
    command: yarn start:mock
  # Setup client
  client:
    build: "./frontend"
    environment:
      - PORT=${REACT_APP_PORT}
      - REACT_APP_API_URL=http://localhost:${API_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./frontend/src:/srv/app/id2207-frontend/src
      - ./frontend/public:/srv/app/id2207-frontend/public
    command: yarn start
    links:
      - server
    stdin_open: true
